Can't use .. with makeRelativeToProject.
When the package is used from another repo it results in the error:

```
bowtie-example> /tmp/stack16232/bowtie-example-0.0.0/src/Bowtie/Example.hs:25:11: error:
bowtie-example>     • Exception when trying to run compile-time code:
bowtie-example>         /tmp/stack16232/bowtie-example-0.0.0/../well-typed-examples: getDirectoryContents:openDirStream: does not exist (No such file or directory)
bowtie-example>       Code: makeRelativeToProject "../well-typed-examples" >>= embedDir
bowtie-example>     • In the untyped splice:
bowtie-example>         $(makeRelativeToProject "../well-typed-examples" >>= embedDir)
bowtie-example>    |
bowtie-example> 25 |   process $(makeRelativeToProject "../well-typed-examples" >>= embedDir)
bowtie-example>    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```